before_install:
  - gem update bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.2
  - 2.3.0
  - ruby-head
  - jruby-19mode
  - jruby
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
